### ISSUE TITLE
360t7固件./scripts/feeds update -a时报错

### ISSUE THREAD

**Issue by tangyl2000** [padavanonly/immortalwrtARM#16]
1、源码获取：
git clone -b mt7981 --single-branch https://github.com/padavanonly/immortalwrtARM
2、执行./scripts/feeds update -a时报错：
Can't exec "": 没有那个文件或目录 at ./scripts/feeds line 835.
3、feeds文件835行内容：
system(`sed -i -e 's/"^rausb%d", "^rai%d", "^ra%d", "^wdsi%d", "^wds%d", "^apclii%d", "^apcli%d", "^apcliusb%d", //' feeds/luci/modules/luci-base/luasrc/model/network.lua`);

求解决~~提前感谢~

已找到答案，请close本issue

**Comment by whatagoodboy** [comment]
@tangyl2000 我也遇到此问题了，麻烦发下解决办法可以吗？谢谢！

**Comment by tangyl2000** [comment]
close

**Comment by tangyl2000** [comment]
close
