### ISSUE TITLE
是否可以提供itb格式的sysupgrade

### ISSUE THREAD

**Issue by izhaohui** [padavanonly/immortalwrtARM#24]
因为刷了原生的openwrt，无法更新bin（是否是分区格式问题？一直失败），是否可提供兼容的更新包

当前刷固件使用itb后缀的包，期望提供

**Comment by jwkinko** [comment]
进uboot 刷 squashfs-sysupgrade.bin 不行吗？

**Comment by izhaohui** [comment]
我自己编译了一个解锁mtd的openwrt，刷了其他版本的bl2，之后通过webui刷机解决了。问题close
