### ISSUE TITLE
nlbwmon、vnstat、wrtbwmon等网络带宽监视器均无法正常监控网络流量

### ISSUE THREAD

**Issue by uparrows** [padavanonly/immortalwrtARM#25]
尝试了nlbwmon、vnstat、wrtbwmon等网络带宽监视器均无法正常监控网络流量，lan口提示无连接，darkstat勉强能用

![01](https://user-images.githubusercontent.com/38988286/228231067-a725124a-9888-422a-b95a-fd8b39f73d99.jpg)

**Comment by InspoOnU** [comment]
无解，除非关闭硬件加速

**Comment by uparrows** [comment]
> 无解，除非关闭硬件加速

了解，谢谢
