### ISSUE TITLE
360T7 内核一直报这个日志shiang! PeerProbeReqSanity failed

### ISSUE THREAD

**Issue by davidtall** [padavanonly/immortalwrtARM#30]
‘’‘
[  843.582849] 7981@C08L1,sync_fsm_peer_request_idle_action() 2168: shiang! PeerProbeReqSanity failed!
[  843.591975] PeerProbeReqSanity() - wrong IE_HT_CAP. eid_len = 0
[  843.597961] 7981@C08L1,sync_fsm_peer_request_idle_action() 2168: shiang! PeerProbeReqSanity failed!
[  843.607235] PeerProbeReqSanity() - wrong IE_HT_CAP. eid_len = 0
[  843.613451] 7981@C08L1,sync_fsm_peer_request_idle_action() 2168: shiang! PeerProbeReqSanity failed!
[  843.622631] PeerProbeReqSanity() - wrong IE_HT_CAP. eid_len = 0
[  843.628575] 7981@C08L1,sync_fsm_peer_request_idle_action() 2168: shiang! PeerProbeReqSanity failed!
[  843.637733] PeerProbeReqSanity() - wrong IE_HT_CAP. eid_len = 0
[  843.643745] 7981@C08L1,sync_fsm_peer_request_idle_action() 2168: shiang! PeerProbeReqSanity failed!
[  843.652906] PeerProbeReqSanity() - wrong IE_HT_CAP. eid_len = 0
[  843.659036] 7981@C08L1,sync_fsm_peer_request_idle_action() 2168: shiang! PeerProbeReqSanity failed!
[  843.818879] 7981@C08L3,ap_peer_auth_req_at_idle_action() 717: AUTH - MBSS(0), Rcv AUTH seq#1, Alg=0, Status=0 from [wcid=1023]02:73:d0:7a:e6:b0
[  843.831823] entrytb_aid_aquire(): found non-occupied aid:5, allocated from:2
[  843.838886] 7981@C13L2,MacTableInsertEntry() 1537: New Sta:02:73:d0:7a:e6:b0
[  843.849485] 7981@C08L3,ap_cmm_peer_assoc_req_action() 1647:  Recv Assoc from STA - 02:73:d0:7a:e6:b0
[  843.858795] 7981@C08L3,ap_cmm_peer_assoc_req_action() 2170: ASSOC Send ASSOC response (Status=0)...
[  843.867904] 7981@C01L3,wifi_sys_conn_act() 1115: wdev idx = 0
[  843.874034] 7981@C08L3,hw_ctrl_flow_v2_connt_act() 215: wdev_idx=0
[  843.996338] 7981@C15L3,WPABuildPairMsg1() 5278: <=== send Msg1 of 4-way
[  844.003035] 7981@C15L3,PeerPairMsg2Action() 6197: ===>Receive msg 2
[  844.009891] 7981@C15L3,WPABuildPairMsg3() 5555: <=== send Msg3 of 4-way
[  844.016620] 7981@C15L3,PeerPairMsg4Action() 6627: ===>Receive msg 4
[  844.028242] 7981@C15L2,PeerPairMsg4Action() 6989: AP SETKEYS DONE(ra0) - AKMMap=WPA2PSK, PairwiseCipher=AES, GroupCipher=TKIP, wcid=4 from 02:73:d0:7a:e6:b0
[  844.028242] 
[  844.105793] PeerProbeReqSanity() - wrong IE_HT_CAP. eid_len = 0
[  844.111728] 7981@C08L1,sync_fsm_peer_request_idle_action() 2168: shiang! PeerProbeReqSanity failed!
[  844.120769] PeerProbeReqSanity() - wrong IE_HT_CAP. eid_len = 0
[  844.126729] 7981@C08L1,sync_fsm_peer_request_idle_action() 2168: shiang! PeerProbeReqSanity failed!

’‘’
启用2.4G wifi 就会出现，只启动5G WIFI 不会出现 @padavanonly

**Comment by rootphantomer** [comment]
我最新的那个版本的内核日志里倒是没有这个PeerProbeReqSanity failed!
