### ISSUE TITLE
360 T7 iPhone 5s无法连接到WiFi

### ISSUE THREAD

**Issue by InspoOnU** [padavanonly/immortalwrtARM#33]
使用了wpa2wpa3或者wpa2以后，iPhone 5s无论怎么连接都提示密码错误。只有关掉加密才能连接。
以前的老版本可以连上，h大的固件现在也没有问题。

**Comment by lalasou** [comment]
> 使用了wpa2wpa3或者wpa2以后，iPhone 5s无论怎么连接都提示密码错误。只有关掉加密才能连接。
> 
> 以前的老版本可以连上，h大的固件现在也没有问题。

遇到过 
WiFi配置乱了
把WiFi重置或者恢复出厂重新设置就行了

**Comment by InspoOnU** [comment]
> > 使用了wpa2wpa3或者wpa2以后，iPhone 5s无论怎么连接都提示密码错误。只有关掉加密才能连接。
> > 以前的老版本可以连上，h大的固件现在也没有问题。
> 
> 遇到过 WiFi配置乱了 把WiFi重置或者恢复出厂重新设置就行了

ios重置网络，wrt恢复出厂都不行

**Comment by padavanonly** [comment]
wpa/wpa2加密呢

**Comment by InspoOnU** [comment]
> wpa/wpa2加密呢

也不行，不过5s应该支持wpa2
