### ISSUE TITLE
纯小白，请问安装别的模块的时候，缺少 kmod-nft-queue 应该怎么办呢，红米ax6000

### ISSUE THREAD

**Issue by bling-yshs** [padavanonly/immortalwrtARM#38]
```
root@ImmortalWrt:/tmp/upload# opkg install ua2f_4.1.2-1_aarch64_cortex-a53.ipk 
Unknown package 'ua2f'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-queue for ua2f
 * pkg_hash_fetch_best_installation_candidate: Packages for ua2f found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package ua2f.
```

就是我安装一个ua2f的模块，但是他需要kmod-nft-queue，这个kmod-nft-queue我只知道在编译的时候可以勾选上，但是编译我又不太会...就是我想知道一下如何才能得到可以适配红米ax6000的kmod-nft-queue的ipk文件呢，最好能具体一点，有步骤的话让我自己单独编译这个ipk也可以QAQ

**Comment by bling-yshs** [comment]
我自己编译出来的是kernel_5.4.224-1-d1af0f9292da0eda76bf47e317e98ae3_aarch64_cortex-a53，但是我固件本身里的是5.4.224-1-7dc39f8990fdc51905241a705930eb9b

**Comment by bling-yshs** [comment]
看起来确实是不行，而且我自己编译出来的也和发在恩山的固件的内容不一样，我target image已经选了xiaomi redmi ax6000 routing什么的，看来是作者加了很多别的模块，那就没办法了QAQ

**Comment by padavanonly** [comment]
直接编译自需要的功能的固件就是了

**Comment by bling-yshs** [comment]
> 直接编译自需要的功能的固件就是了

大佬请问自己编译出来的固件会合并分区吗？我怕刷砖了回不去了等下😭

**Comment by bling-yshs** [comment]
已解决，自己从头编译成功了
