### ISSUE TITLE
why kernel 5.10 and 5.15 is dead?

### ISSUE THREAD

**Issue by bricco1981** [padavanonly/immortalwrtARM#4]
why on this commit only 5.4 kernel is supported

**Comment by bricco1981** [comment]
also you need fix bootcount, some devices does not work right on 2.4 ghz.

ifconfig apclii0 up
	ifconfig rai0 up
	ifconfig apcli0 up
	ifconfig ra0 up
	/etc/init.d/apcli.sh start
	mtkwifi reload

**Comment by padavanonly** [comment]
It's based on https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/  so there is only linux 5.4 support.

“some devices does not work right on 2.4 ghz” What does this mean?  Can you explain  it more clearly？

**Comment by bricco1981** [comment]
it caused disconnection problems for only two devices, after i added ifconfig apclio up, to the bootcount the disconnection problems disappeared.
