### ISSUE TITLE
ax6000 Patch failed!  Please fix ./patches/006-bw.patch!

### ISSUE THREAD

**Issue by yho2ds** [padavanonly/immortalwrtARM#43]
Applying ./patches/001-eeprom-flash-api.patch using plaintext:
patching file mt_wifi/embedded/common/ee_flash.c

Applying ./patches/002-sort-site-survey-table.patch using plaintext:
patching file mt_wifi/embedded/common/cmm_info.c
Hunk #1 succeeded at 6793 (offset 88 lines).

Applying ./patches/003-fix-rxrate-stainfo.patch using plaintext:
patching file mt_wifi/embedded/common/cmm_info.c
Hunk #1 succeeded at 6987 (offset 89 lines).
Hunk #2 succeeded at 7027 (offset 89 lines).
Hunk #3 succeeded at 7056 (offset 89 lines).

Applying ./patches/004-remove-apcli-bgprotect-log.patch using plaintext:
patching file mt_wifi/embedded/fsm/sta_mgmt_sync.c
Hunk #1 succeeded at 500 (offset 17 lines).

Applying ./patches/005-use-ext-warp-code.patch using plaintext:
patching file mt_wifi_ap/Makefile
Hunk #1 succeeded at 13 (offset 1 line).

Applying ./patches/006-bw.patch using plaintext:
patching file mt_wifi/embedded/ap/ap.c
Hunk #1 FAILED at 3962.
1 out of 1 hunk FAILED -- saving rejects to file mt_wifi/embedded/ap/ap.c.rej
patching file mt_wifi/embedded/ap/ap_cfg.c
Hunk #1 succeeded at 422 with fuzz 2 (offset 2 lines).
Hunk #2 FAILED at 1253.
Hunk #3 succeeded at 14588 (offset 31 lines).
1 out of 3 hunks FAILED -- saving rejects to file mt_wifi/embedded/ap/ap_cfg.c.rej
patching file mt_wifi/embedded/fsm/sta_mgmt_cntl.c
Hunk #1 FAILED at 2850.
Hunk #2 succeeded at 4207 with fuzz 2 (offset 764 lines).
1 out of 2 hunks FAILED -- saving rejects to file mt_wifi/embedded/fsm/sta_mgmt_cntl.c.rej
patching file mt_wifi/embedded/include/rtmp.h
Hunk #1 FAILED at 2971.
1 out of 1 hunk FAILED -- saving rejects to file mt_wifi/embedded/include/rtmp.h.rej
patching file mt_wifi/embedded/mgmt/mgmt_he.c
Hunk #1 FAILED at 2326.
1 out of 1 hunk FAILED -- saving rejects to file mt_wifi/embedded/mgmt/mgmt_he.c.rej
patching file mt_wifi/embedded/mgmt/mgmt_vht.c
Hunk #1 FAILED at 636.
1 out of 1 hunk FAILED -- saving rejects to file mt_wifi/embedded/mgmt/mgmt_vht.c.rej
Patch failed!  Please fix ./patches/006-bw.patch!
make[3]: *** [Makefile:354: /home/hq/immortalwrtARM/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7986/mt_wifi/.prepared_b6f9370efc94b5651ce0f6e8f2540560_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/hq/immortalwrtARM/package/mtk/drivers/mt_wifi'
time: package/mtk/drivers/mt_wifi/compile#0.12#0.11#0.21
    ERROR: package/mtk/drivers/mt_wifi failed to build.
make[2]: *** [package/Makefile:116: package/mtk/drivers/mt_wifi/compile] Error 1
make[2]: Leaving directory '/home/hq/immortalwrtARM'
make[1]: *** [package/Makefile:110: /home/hq/immortalwrtARM/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/hq/immortalwrtARM'
make: *** [/home/hq/immortalwrtARM/include/toplevel.mk:230: world] Error 2
应用失败了

**Comment by padavanonly** [comment]
fixed
